# Generated by Django 3.1.7 on 2021-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210225_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='login.User'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
