# Generated by Django 3.1.7 on 2021-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_friends'),
        ('planner', '0004_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invitees',
            field=models.ManyToManyField(related_name='invited_to', to='login.User'),
        ),
    ]
